-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE QTY_COUNTRY 
    ( 
     COUNTRY_NAME VARCHAR2 (64)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_COUNTRY.COUNTRY_NAME IS 'WEB SERIES RELEASING COUNTRY NAME' 
;

ALTER TABLE QTY_COUNTRY 
    ADD CONSTRAINT QTY_COUNTRY_PK PRIMARY KEY ( COUNTRY_NAME ) ;

CREATE TABLE QTY_DUBBING_LANGUAGE 
    ( 
     DUBBING_LANGUAGE_ID VARCHAR2 (10)  NOT NULL , 
     LANGUAGE_NAME       VARCHAR2 (20)  NOT NULL , 
     WEBSERIES_ID        VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_DUBBING_LANGUAGE.DUBBING_LANGUAGE_ID IS 'DUBBING LANGUAGE ID' 
;

COMMENT ON COLUMN QTY_DUBBING_LANGUAGE.LANGUAGE_NAME IS 'DUBBING LANGUAGE NAME' 
;

COMMENT ON COLUMN QTY_DUBBING_LANGUAGE.WEBSERIES_ID IS 'WEB SERIES ID' 
;

ALTER TABLE QTY_DUBBING_LANGUAGE 
    ADD CONSTRAINT QTY_DUBBING_LANGUAGE_PK PRIMARY KEY ( DUBBING_LANGUAGE_ID ) ;

CREATE TABLE QTY_EPISODE 
    ( 
     EPISODE_ID     VARCHAR2 (10)  NOT NULL , 
     EPISODE_NUMBER VARCHAR2 (10)  NOT NULL , 
     TITLE          VARCHAR2 (64) , 
     WEBSERIES_ID   VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_EPISODE.EPISODE_ID IS 'EPISODE ID' 
;

COMMENT ON COLUMN QTY_EPISODE.EPISODE_NUMBER IS 'EPISODE NUMBER' 
;

COMMENT ON COLUMN QTY_EPISODE.TITLE IS 'EPISODE TITLE' 
;

COMMENT ON COLUMN QTY_EPISODE.WEBSERIES_ID IS 'WEB SERIES ID' 
;

ALTER TABLE QTY_EPISODE 
    ADD CONSTRAINT QTY_EPISODE_PK PRIMARY KEY ( EPISODE_ID ) ;

CREATE TABLE QTY_FEEDBACK 
    ( 
     FEEDBACK_ID   VARCHAR2 (10)  NOT NULL , 
     RATING        NUMBER (1)  NOT NULL , 
     FEEDBACK_TEXT VARCHAR2 (128)  NOT NULL , 
     FEEDBACK_DATE DATE  NOT NULL , 
     ACCOUNT_ID    VARCHAR2 (10)  NOT NULL , 
     WEBSERIES_ID  VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_FEEDBACK.FEEDBACK_ID IS 'FEEDBACK ID' 
;

COMMENT ON COLUMN QTY_FEEDBACK.RATING IS 'FEEDBACK RATING' 
;

COMMENT ON COLUMN QTY_FEEDBACK.FEEDBACK_TEXT IS 'FEEDBACK TEXT' 
;

COMMENT ON COLUMN QTY_FEEDBACK.FEEDBACK_DATE IS 'FEEDBACK DATE' 
;

COMMENT ON COLUMN QTY_FEEDBACK.ACCOUNT_ID IS 'ACCOUNT ID' 
;

COMMENT ON COLUMN QTY_FEEDBACK.WEBSERIES_ID IS 'WEB SERIES ID' 
;
CREATE UNIQUE INDEX QTY_FEEDBACK__IDX ON QTY_FEEDBACK 
    ( 
     WEBSERIES_ID ASC 
    ) 
;

ALTER TABLE QTY_FEEDBACK 
    ADD CONSTRAINT QTY_FEEDBACK_CK_1 
    CHECK (RATING IN (1,2,3,4,5))
;
ALTER TABLE QTY_FEEDBACK 
    ADD CONSTRAINT QTY_FEEDBACK_PK PRIMARY KEY ( FEEDBACK_ID ) ;

CREATE TABLE QTY_PRODUCER 
    ( 
     PRODUCER_ID VARCHAR2 (10)  NOT NULL , 
     FIRST_NAME  VARCHAR2 (64)  NOT NULL , 
     MIDDLE_NAME VARCHAR2 (64) , 
     LAST_NAME   VARCHAR2 (64)  NOT NULL , 
     PHONE       NUMBER (10)  NOT NULL , 
     STREET      VARCHAR2 (64)  NOT NULL , 
     CITY        VARCHAR2 (64)  NOT NULL , 
     STATE       VARCHAR2 (32)  NOT NULL , 
     EMAIL       VARCHAR2 (64)  NOT NULL , 
     NATIONALITY VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_PRODUCER.PRODUCER_ID IS 'PRODUCER ID' 
;

COMMENT ON COLUMN QTY_PRODUCER.FIRST_NAME IS 'PRODUCER''S FIRST NAME' 
;

COMMENT ON COLUMN QTY_PRODUCER.MIDDLE_NAME IS 'PRODUCER''S MIDDLE NAME' 
;

COMMENT ON COLUMN QTY_PRODUCER.LAST_NAME IS 'PRODUCER''S LAST NAME' 
;

COMMENT ON COLUMN QTY_PRODUCER.PHONE IS 'PRODUCER''S PHONE NUMBER' 
;

COMMENT ON COLUMN QTY_PRODUCER.STREET IS 'PRODUCER''S STREET ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCER.CITY IS 'PRODUCER''S CITY ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCER.STATE IS 'PRODUCER''S STATE ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCER.EMAIL IS 'PRODUCER''S EMAIL ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCER.NATIONALITY IS 'PRODUCER''S NATIONALITY' 
;

ALTER TABLE QTY_PRODUCER 
    ADD CONSTRAINT QTY_PRODUCER_PK PRIMARY KEY ( PRODUCER_ID ) ;

ALTER TABLE QTY_PRODUCER 
    ADD CONSTRAINT QTY_PRODUCER__UN UNIQUE ( EMAIL ) ;

CREATE TABLE QTY_PRODUCER_AFFILIATION 
    ( 
     START_DATE  DATE  NOT NULL , 
     END_DATE    DATE , 
     PRODUCER_ID VARCHAR2 (10)  NOT NULL , 
     HOUSE_ID    VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_PRODUCER_AFFILIATION.START_DATE IS 'AFFILIATION START DATE' 
;

COMMENT ON COLUMN QTY_PRODUCER_AFFILIATION.END_DATE IS 'AFFILIATION END DATE' 
;

COMMENT ON COLUMN QTY_PRODUCER_AFFILIATION.PRODUCER_ID IS 'PRODUCER ID' 
;

COMMENT ON COLUMN QTY_PRODUCER_AFFILIATION.HOUSE_ID IS 'PRODUCTION HOUSE ID' 
;

ALTER TABLE QTY_PRODUCER_AFFILIATION 
    ADD CONSTRAINT QTY_PRODUCER_AFFILIATION_PK PRIMARY KEY ( PRODUCER_ID, HOUSE_ID ) ;

CREATE TABLE QTY_PRODUCTION_HOUSE 
    ( 
     HOUSE_ID         VARCHAR2 (10)  NOT NULL , 
     NAME             VARCHAR2 (64)  NOT NULL , 
     YEAR_ESTABLISHED VARCHAR2 (10)  NOT NULL , 
     STREET           VARCHAR2 (64)  NOT NULL , 
     CITY             VARCHAR2 (64)  NOT NULL , 
     STATE            VARCHAR2 (64)  NOT NULL , 
     NATIONALITY      VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.HOUSE_ID IS 'PRODUCTION HOUSE ID' 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.NAME IS 'PRODUCTION HOUSE NAME' 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.YEAR_ESTABLISHED IS 'YEAR ESTABLISHED' 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.STREET IS 'PRODUCTION HOUSE STREET ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.CITY IS 'PRODUCTION HOUSE CITY ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.STATE IS 'PRODUCTION HOUSE STATE ADDRESS' 
;

COMMENT ON COLUMN QTY_PRODUCTION_HOUSE.NATIONALITY IS 'PRODUCTION HOUSE NATIONALITY' 
;

ALTER TABLE QTY_PRODUCTION_HOUSE 
    ADD CONSTRAINT QTY_PRODUCTION_HOUSE_PK PRIMARY KEY ( HOUSE_ID ) ;

CREATE TABLE QTY_SERIES_CONTRACT 
    ( 
     CONTRACT_ID        VARCHAR2 (10)  NOT NULL , 
     SIGNED_DATE        DATE  NOT NULL , 
     START_DATE         DATE  NOT NULL , 
     END_DATE           DATE  NOT NULL , 
     CHARGE_PER_EPISODE NUMBER (7,2)  NOT NULL , 
     STATUS             VARCHAR2 (16)  NOT NULL , 
     WEBSERIES_ID       VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.CONTRACT_ID IS 'CONTRACT ID' 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.SIGNED_DATE IS 'CONTRACT SIGN DATE' 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.START_DATE IS 'CONTRACT START DATE' 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.END_DATE IS 'CONTRACT END DATE' 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.CHARGE_PER_EPISODE IS 'CHARGE PER EPISODE' 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.STATUS IS 'CONTRACT STATUS' 
;

COMMENT ON COLUMN QTY_SERIES_CONTRACT.WEBSERIES_ID IS 'WEB SERIES ID' 
;

ALTER TABLE QTY_SERIES_CONTRACT 
    ADD CONSTRAINT QTY_SERIES_CONTRACT_CK_1 
    CHECK (CHARGE_PER_EPISODE>0)
;
ALTER TABLE QTY_SERIES_CONTRACT 
    ADD CONSTRAINT QTY_SERIES_CONTRACT_PK PRIMARY KEY ( CONTRACT_ID ) ;

CREATE TABLE QTY_SUBTITLE_LANGUAGE 
    ( 
     SUBTITLE_LANGUAGE_ID VARCHAR2 (10)  NOT NULL , 
     LANGUAGE_NAME        VARCHAR2 (20)  NOT NULL , 
     WEBSERIES_ID         VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_SUBTITLE_LANGUAGE.SUBTITLE_LANGUAGE_ID IS 'SUBTITLE LANGUAGE ID' 
;

COMMENT ON COLUMN QTY_SUBTITLE_LANGUAGE.LANGUAGE_NAME IS 'SUBTITLE LANGUAGE NAME' 
;

COMMENT ON COLUMN QTY_SUBTITLE_LANGUAGE.WEBSERIES_ID IS 'WEB SERIES ID' 
;

ALTER TABLE QTY_SUBTITLE_LANGUAGE 
    ADD CONSTRAINT QTY_SUBTITLE_LANGUAGE_PK PRIMARY KEY ( SUBTITLE_LANGUAGE_ID ) ;

CREATE TABLE QTY_TELECAST 
    ( 
     TELECAST_ID       VARCHAR2 (10)  NOT NULL , 
     START_DATE        DATE  NOT NULL , 
     END_DATE          DATE  NOT NULL , 
     TECH_INTERRUPTION VARCHAR2 (1)  NOT NULL , 
     TOTAL_VIEWERS     NUMBER (16)  NOT NULL , 
     EPISODE_ID        VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_TELECAST.TELECAST_ID IS 'EPISODE TITLE' 
;

COMMENT ON COLUMN QTY_TELECAST.START_DATE IS 'START DATE & TIME OF THE EPISODES' 
;

COMMENT ON COLUMN QTY_TELECAST.END_DATE IS 'END DATE & TIME OF THE EPISODES' 
;

COMMENT ON COLUMN QTY_TELECAST.TECH_INTERRUPTION IS 'TECHNICAL INTERRUPTION IN TELECAST, IF ANY' 
;

COMMENT ON COLUMN QTY_TELECAST.TOTAL_VIEWERS IS 'TOTAL NUMBER OF VIEWERS' 
;

ALTER TABLE QTY_TELECAST 
    ADD CONSTRAINT QTY_TELECAST_CK_1 
    CHECK (START_DATE<END_DATE)
;


ALTER TABLE QTY_TELECAST 
    ADD CONSTRAINT QTY_TELECAST_CK_2 
    CHECK (TOTAL_VIEWERS>=0)
;


ALTER TABLE QTY_TELECAST 
    ADD CONSTRAINT QTY_TELECAST_CK_3 
    CHECK (TECH_INTERRUPTION IN ('Y','N'))
;
ALTER TABLE QTY_TELECAST 
    ADD CONSTRAINT QTY_TELECAST_PK PRIMARY KEY ( TELECAST_ID ) ;

CREATE TABLE QTY_VIEWER_ACCOUNT 
    ( 
     ACCOUNT_ID             VARCHAR2 (10)  NOT NULL , 
     FIRST_NAME             VARCHAR2 (30)  NOT NULL , 
     MIDDLE_NAME            VARCHAR2 (30) , 
     LAST_NAME              VARCHAR2 (30)  NOT NULL , 
     STREET                 VARCHAR2 (64)  NOT NULL , 
     CITY                   VARCHAR2 (64)  NOT NULL , 
     STATE                  VARCHAR2 (64)  NOT NULL , 
     OPEN_DATE              DATE  NOT NULL , 
     MONTHLY_SERVICE_CHARGE NUMBER (10,2)  NOT NULL , 
     COUNTRY_NAME           VARCHAR2 (64)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.ACCOUNT_ID IS 'ACCOUNT ID' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.FIRST_NAME IS 'ACCOUNT OWNER FIRST NAME' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.MIDDLE_NAME IS 'ACCOUNT OWNER MIDDLE NAME' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.LAST_NAME IS 'ACCOUNT OWNER LAST NAME' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.STREET IS 'ACCOUNT OWNER STREET ADDRESS' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.CITY IS 'ACCOUNT OWNER CITY ADDRESS' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.STATE IS 'ACCOUNT OWNER STATE ADDRESS' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.OPEN_DATE IS 'ACCOUNT OPEN DATE' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.MONTHLY_SERVICE_CHARGE IS 'MONTHLY SERVICE CHARGE' 
;

COMMENT ON COLUMN QTY_VIEWER_ACCOUNT.COUNTRY_NAME IS 'ACCOUNT OWNER COUNTRY NAME' 
;

ALTER TABLE QTY_VIEWER_ACCOUNT 
    ADD CONSTRAINT QTY_VIEWER_ACCOUNT_PK PRIMARY KEY ( ACCOUNT_ID ) ;

CREATE TABLE QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID VARCHAR2 (10)  NOT NULL , 
     TITLE        VARCHAR2 (64)  NOT NULL , 
     NUM_EPISODES  NUMBER (8)  NOT NULL , 
     TYPE         VARCHAR2 (15)  NOT NULL , 
     HOUSE_ID     VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_WEB_SERIES.WEBSERIES_ID IS 'WEB SERIES ID' 
;

COMMENT ON COLUMN QTY_WEB_SERIES.TITLE IS 'WEB SERIES TITLE' 
;

COMMENT ON COLUMN QTY_WEB_SERIES.num_episodes IS 'NUMBER OF EPISODES' 
;

COMMENT ON COLUMN QTY_WEB_SERIES.TYPE IS 'WEB SERIES TYPE' 
;

COMMENT ON COLUMN QTY_WEB_SERIES.HOUSE_ID IS 'PRODUCTION HOUSE ID' 
;

ALTER TABLE QTY_WEB_SERIES 
    ADD CONSTRAINT QTY_WEB_SERIES_PK PRIMARY KEY ( WEBSERIES_ID ) ;

CREATE TABLE QTY_WEB_SERIES_RELEASE 
    ( 
     RELEASE_DATE DATE  NOT NULL , 
     WEBSERIES_ID VARCHAR2 (10)  NOT NULL , 
     COUNTRY_NAME VARCHAR2 (64)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QTY_WEB_SERIES_RELEASE.RELEASE_DATE IS 'WEB SERIES RELEASE DATE' 
;

COMMENT ON COLUMN QTY_WEB_SERIES_RELEASE.WEBSERIES_ID IS 'WEB SERIES ID' 
;

COMMENT ON COLUMN QTY_WEB_SERIES_RELEASE.COUNTRY_NAME IS 'WEB SERIES RELEASING COUNTRY NAME' 
;

ALTER TABLE QTY_WEB_SERIES_RELEASE 
    ADD CONSTRAINT QTY_WEB_SERIES_RELEASE_PK PRIMARY KEY ( WEBSERIES_ID, COUNTRY_NAME ) ;

ALTER TABLE QTY_VIEWER_ACCOUNT 
    ADD CONSTRAINT QTY_ACC_QTY_COU_FK FOREIGN KEY 
    ( 
     COUNTRY_NAME
    ) 
    REFERENCES QTY_COUNTRY 
    ( 
     COUNTRY_NAME
    ) 
;

ALTER TABLE QTY_SERIES_CONTRACT 
    ADD CONSTRAINT QTY_CON_QTY_SER_FK FOREIGN KEY 
    ( 
     WEBSERIES_ID
    ) 
    REFERENCES QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID
    ) 
;

ALTER TABLE QTY_DUBBING_LANGUAGE 
    ADD CONSTRAINT QTY_DLAN_QTY_SER_FK FOREIGN KEY 
    ( 
     WEBSERIES_ID
    ) 
    REFERENCES QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID
    ) 
;

ALTER TABLE QTY_EPISODE 
    ADD CONSTRAINT QTY_EPI_QTY_SER_FK FOREIGN KEY 
    ( 
     WEBSERIES_ID
    ) 
    REFERENCES QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID
    ) 
;

ALTER TABLE QTY_FEEDBACK 
    ADD CONSTRAINT QTY_FEE_QTY_ACC_FK FOREIGN KEY 
    ( 
     ACCOUNT_ID
    ) 
    REFERENCES QTY_VIEWER_ACCOUNT 
    ( 
     ACCOUNT_ID
    ) 
;

ALTER TABLE QTY_FEEDBACK 
    ADD CONSTRAINT QTY_FEE_QTY_SER_FK FOREIGN KEY 
    ( 
     WEBSERIES_ID
    ) 
    REFERENCES QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID
    ) 
;

ALTER TABLE QTY_PRODUCER_AFFILIATION 
    ADD CONSTRAINT QTY_PRO_QTY_PROH_FK FOREIGN KEY 
    ( 
     PRODUCER_ID
    ) 
    REFERENCES QTY_PRODUCER 
    ( 
     PRODUCER_ID
    ) 
;

ALTER TABLE QTY_PRODUCER_AFFILIATION 
    ADD CONSTRAINT QTY_PROA_QTY_PROH_FK FOREIGN KEY 
    ( 
     HOUSE_ID
    ) 
    REFERENCES QTY_PRODUCTION_HOUSE 
    ( 
     HOUSE_ID
    ) 
;

ALTER TABLE QTY_WEB_SERIES 
    ADD CONSTRAINT QTY_SER_QTY_PROH_FK FOREIGN KEY 
    ( 
     HOUSE_ID
    ) 
    REFERENCES QTY_PRODUCTION_HOUSE 
    ( 
     HOUSE_ID
    ) 
;

ALTER TABLE QTY_WEB_SERIES_RELEASE 
    ADD CONSTRAINT QTY_SER_REL_QTY_COU_FK FOREIGN KEY 
    ( 
     COUNTRY_NAME
    ) 
    REFERENCES QTY_COUNTRY 
    ( 
     COUNTRY_NAME
    ) 
;

ALTER TABLE QTY_WEB_SERIES_RELEASE 
    ADD CONSTRAINT QTY_SER_REL_QTY_SER_FK FOREIGN KEY 
    ( 
     WEBSERIES_ID
    ) 
    REFERENCES QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID
    ) 
;

ALTER TABLE QTY_SUBTITLE_LANGUAGE 
    ADD CONSTRAINT QTY_SLAN_QTY_SER_FK FOREIGN KEY 
    ( 
     WEBSERIES_ID
    ) 
    REFERENCES QTY_WEB_SERIES 
    ( 
     WEBSERIES_ID
    ) 
;

ALTER TABLE QTY_TELECAST 
    ADD CONSTRAINT QTY_TEL_QTY_EPI_FK FOREIGN KEY 
    ( 
     EPISODE_ID
    ) 
    REFERENCES QTY_EPISODE 
    ( 
     EPISODE_ID
    ) 
;